### ISSUE TITLE
Peer-to-peer Review

### ISSUE THREAD

**Issue by Lockless404** [addisalemseifu/AusomeBooks#6]
Excellent work Dire and Addisalem. Everything looks good.

**Comment by AtillaTahak** [comment]
- Live View doesn't work on the readme

**Comment by GintsM** [comment]
Ok Nice work, About display method, my suggestion is to make a loop outside of this method. to keep you possibilities vary with functionality(as described earlier). And I like your approach to show and hide pages, simple but very clear.
